acti_func: ReLU
batch_first: false
batch_size: 256
gcn_drop: 0.2
graph_pool: sum
hidden_size: 64
input_size: 4
learning_rate: 8.0e-05
num_features: 4
optim: Adam
output_dim: 1
sentence_nodes: 1
seq_weight: 0.5
slstm_drop: 0.0
steps: 9
struc_weight: 0.5
window_size: 3
